- clock:
    format: "hh:mm A"
    timezone: "America/New_York"

- search:
    provider: "duckduckgo"
    target: "_blank"

- unifi_controller:
    widget:
      type: unifi
      url: https://nuc-1.local:8443
      username: "YOUR_USERNAME"
      password: "YOUR_PASSWORD"

- caddy:
    url: http://nuc-1.local:2019


