---
# Information widgets appear at the top of the homepage
- logo:
    icon: mdi-home

- datetime:
    text_size: xl
    format:
      dateStyle: short
      timeStyle: short
      hourCycle: h12

- search:
    provider: duckduckgo
    target: _blank



